### ISSUE TITLE
Commenting on Django Templates incorrect

### ISSUE THREAD

**Issue by willvanwazer** [squ1b3r/Djaneiro#10]
When the shortcut for commenting is pressed (Command - / ), comments are presented as standard HTML, rather than Django templates (as with the TextMate bundle).

**Comment by admed** [comment]
How is the progress on this issue?

**Comment by squ1b3r** [comment]
I don't really think something will change here until ST3 starts recognizing `TM_COMMENT_MODE` or adds something similar.

**Comment by dggsax** [comment]
This probably goes against the purpose of Djaneiro but would it be possible just make Command + / just do normal  when working with HTML files? Or just modify like the above comments mentioned.

**Comment by chrisconlan** [comment]
I think the community needs a pared down version of this package that just handles syntax highlighting and common ST3 shortcuts like `Ctrl+/`. I'll start it.

https://github.com/ConlanHoldings/django-highlite

**Comment by asfaltboy** [comment]
@chrisconlan can I use django-highlite alongside Djaneiro (for the python-django snippets) ?

**Comment by chrisconlan** [comment]
I haven't tried. If you include django-highlite after djaniero, my commenting shortcut might override the existing one and achieve your desired effect.

**Comment by asfaltboy** [comment]
It does work beautifully, thanks for making it!

**Comment by willstott101** [comment]
I created a new [repo specifically to work on using the new syntax highlighting engine](https://github.com/willstott101/django-sublime-syntax) in ST3... however there still seem to be no reasonable solution to our comments problem. @squ1b3r did you ever open an issue at https://github.com/sublimehq/sublime_text/issues ?

FYI #123 brings this modern syntax highlighting to Djaneiro too.

**Comment by squ1b3r** [comment]
>  @squ1b3r did you ever open an issue at https://github.com/sublimehq/sublime_text/issues ?
@willstott101 There were a number of issues related to that a few years back and I'm not sure if any of those were resolved to be honest.
