### ISSUE TITLE
HTML syntax issue with sublime 3dev (build 3113)

### ISSUE THREAD

**Issue by karolyi** [squ1b3r/Djaneiro#107]
Hey,

using the newest sublime 3dev build, I get the following error:

![image](https://cloud.githubusercontent.com/assets/987055/15211342/fda86262-183a-11e6-8595-603bfc36325a.png)

also, as you can see, the html syntax is busted.

**Comment by squ1b3r** [comment]
Tried with build 3114. Everything works fine. So it was either a bug in build 3113 or you have something messed up in your setup.

**Comment by karolyi** [comment]
where did you get 3114 from? I'm on 3dev but no update yet.

it might well be that it was a problem in sublime, I since encountered that bug with other html-like syntaxes too.

**Comment by squ1b3r** [comment]
Erm, main page? https://www.sublimetext.com/3

**Comment by karolyi** [comment]
well, the dev branch doesn't follow the stable then. like I said I'm on 3dev (https://www.sublimetext.com/3dev) and that doesn't have 3114. I'll open an issue regarding that too.

just installed 3114 and still getting the error message. let me do a clean install and report back if the problem persists with that too.

**Comment by karolyi** [comment]
ok, found the culprit:

https://github.com/crisward/sublime-tag/issues/7

deinstalling riot-tag (not using it anyways) helped.

**Comment by squ1b3r** [comment]
Good to know. Thanks.
