### ISSUE TITLE
Are we supporting DRF

### ISSUE THREAD

**Issue by girishkumarkh** [squ1b3r/Djaneiro#108]
[**Django Rest Framework**](https://github.com/tomchristie/django-rest-framework) is one of the popular frameworks for Django and its received well by wide community. 
can semantics such as following can be supported by us? - if so it could be very useful!
```
serializers.Serializer
serializers.ModelSerializer
serializers.HyperlinkedModelSerializer
serializers.ListSerializer
serializers.BaseSerializer
. . . and many more
```
Let me know if anyone is working on supporting for DRF

**Comment by squ1b3r** [comment]
Djaneiro is a collection of snippets for Django's template tags and filters in the first place. Peronally I would like to keep is that way. I don't think mixing it with any of those Django apps would do any good here. And it has reason to ve here to be honest. Can always be made as a separate plugin I guess.

**Comment by girishkumarkh** [comment]
Sure, makes sense! Thanks for the head up.
