### ISSUE TITLE
Mistake HTML to HTML(django)

### ISSUE THREAD

**Issue by eromoe** [squ1b3r/Djaneiro#109]
It often set regular html file from `HTML` to `HTML(django)`, which make shortcut `ctrl-/` change from `<!-- !-->` to `{# #}`. I don't know why.

Doesn't it detect if content has some syntax like `{% %}` at first, then change file to `HTML(django)`?
And javascript and css don't work well(without smart) on `HTML(django)`.

**Comment by squ1b3r** [comment]
Djaneiro is activated by default for any *.html files. It does not detect anything because it makes no sense. If you don't like this behaviour you can remove *.html from Djaneiro settings but then you will have to manually activate it every time when you need HTML(django).
