### ISSUE TITLE
Wrong syntax highlight in HTML

### ISSUE THREAD

**Issue by andrius-senulis** [squ1b3r/Djaneiro#111]
Hi,

I'm experiencing the text being colored in white when I use:

```html
<select>
    <option value="1">{% if var1 == var2 %}text here{% endif %}</option>
    <option value="2">{% if var3 == var4 %}text here{% endif %}</option>
</select>
```

All the text is in white from `==` until the next `=` sign. I suspect that this is something to do with Django version, probably Djaneiro uses the syntax of the latest Django while I am using v1.8. If that's the case, is there a setting in Djaneiro to change syntax highlighting depending on Django version?

Cheers,
Andrius

**Comment by squ1b3r** [comment]
<img width="660" alt="screenshot 2016-09-13 09 10 34" src="https://cloud.githubusercontent.com/assets/221821/18481711/0efeae46-7992-11e6-8432-de029ad52f47.png">

Hi. Works absolutely fine here. Djaneiro has no connection to Django version. Check your color scheme.
