### ISSUE TITLE
Update Readme for Sublime 3

### ISSUE THREAD

**Issue by anweshknayak** [squ1b3r/Djaneiro#114]

**Comment by squ1b3r** [comment]
@anweshknayak Care to elaborate? What's need to be updated?

**Comment by anweshknayak** [comment]
OS X: ~/Library/Application\ Support/Sublime\ Text\ 2/Packages
Windows: %APPDATA%/Sublime Text 2/Packages/
Linux: ~/.config/sublime-text-2/Packages

to 3. Newbies might get confused. Said from their POV. Close this issue if sounds irrelevant

**Comment by squ1b3r** [comment]
Updated things a bit. Thanks for reminding me.
