### ISSUE TITLE
script tag highlighting in 3126

### ISSUE THREAD

**Issue by kmo1** [squ1b3r/Djaneiro#115]
I'm noticing that script tags are causing issues w/ djaneiro.

![image](https://cloud.githubusercontent.com/assets/6374601/23032439/3829b2fe-f429-11e6-9fb4-b8e650a34a7c.png)

It looks like it thinks that there's an extra tag because if I add a closing tag the issue goes away

![image](https://cloud.githubusercontent.com/assets/6374601/23032488/59b37572-f429-11e6-9084-b81d0183cde4.png)

Also, I'd expect an html comment to work, but...

![image](https://cloud.githubusercontent.com/assets/6374601/23032514/6b88f92a-f429-11e6-94c5-7a344bc69379.png)

it looks as though it thinks that this is still an open script tag

![image](https://cloud.githubusercontent.com/assets/6374601/23032534/7b3b5dc2-f429-11e6-8aed-96b5b34223b1.png)

**Comment by squ1b3r** [comment]
<img width="902" alt="screenshot 2017-02-16 09 35 42" src="https://cloud.githubusercontent.com/assets/221821/23033002/55b56e56-f42b-11e6-8455-81fb95801f19.png">

Nothing like this on my end. Tried different built-in and custom color schemes as well. So my guess is that something is off with your HTML layout. Maybe you forgot to close something before the script definition.
