### ISSUE TITLE
Weird Bracket({}) completion

### ISSUE THREAD

**Issue by bombs-kim** [squ1b3r/Djaneiro#116]
I think I found a bug. In some situations I found that bracket completions work incorrectly. The closing brackets are added in wrong places to be specific. Here I prepared a case. If you want to replicate this, plz note that if and endif tags are indented and there are four spaces added in the line between them.

![image](https://cloud.githubusercontent.com/assets/11001573/26518544/84edbf78-42ed-11e7-9fee-f7ebac6eaab0.png)
![image](https://cloud.githubusercontent.com/assets/11001573/26518560/bbdb1a12-42ed-11e7-9bd7-723eda029a54.png)

![image](https://cloud.githubusercontent.com/assets/11001573/26518550/a0da4486-42ed-11e7-93ee-cd6465688f1b.png)
![image](https://cloud.githubusercontent.com/assets/11001573/26518552/a86923f2-42ed-11e7-86d6-349f1d5c8e42.png)

I guess the screen shots are self explaining, so I won't explain more. Thank you!

**Comment by scuml** [comment]
Seems to be a sublime issue that was fixed.  Can close.
