### ISSUE TITLE
tab vs space insertion in Model snippet

### ISSUE THREAD

**Issue by whittredge** [squ1b3r/Djaneiro#121]
Hi,

Great plugin, thanks for your work.

On my setup the `Model` snippet inserts 4 spaces instead of tab, even though all other snippets are inserting tabs.   It seems like this might be a source inconsistency that needs to be changed, since only this one snippet is affected.  (The 4 space indentation causes an error at build for me.)

Paul

**Comment by scuml** [comment]
All multi-line snippets use spaces as spaces are the PEP8 recommended style.  It's possible single line snippets will be indented using the pages tab settings.
