### ISSUE TITLE
Imports auto ordering on save

### ISSUE THREAD

**Issue by mightym** [squ1b3r/Djaneiro#122]
I'm a bit confused. Since today when I save my python files Djaneiro seems to order my imports alphabetically. When I disable djaneiro no re-ordering happens. Is this a feature of Djaneiro? If so how can I disable it? If not is this possibly a bug?

**Comment by squ1b3r** [comment]
@mightym Djaneiro is just a set of snippets. It has nothing that can affect your imports.

**Comment by mightym** [comment]
Ok thanks!
