### ISSUE TITLE
Djaneiro Syntax Highlighting have stopped working

### ISSUE THREAD

**Issue by Afrowave** [squ1b3r/Djaneiro#126]
Hi @squ1b3r 

Thanks for the good work you have done on this and I know that the version I am using is not the stated ones that it should work under. However, SublimeHQ has stated that version 4 should be backwards compatible with version 3 and the package has been working well until this version. 

\## What happened?

I updated my Sublime Text to 4087 and Sublime Merge to 2034 and  on start up of both, I received the error,

"**Error loading syntax file "Packages/Djaneiro/Syntaxes/HTML (Django).tmLanguage": Apparent recursion within a with\_prototype action: 25000 context sanity limit hit"**

\## What should've happened instead?

There should have been no warning. Djaneiro should work as expected.

\## Additional details

> Changelog: 
> 
> \* Various syntax highlighting improvements 
> 
> \* OpenGL rendering performance improvements 
> 
> \* Syntax Definitions: Added symbol indexing tests 
> 
> \* Syntax Definitions: Added more information to the Show Scope Name popup 
> 
> \* Syntax Definitions: Renamed TypeScript to TSX, and added a new vanilla TypeScript syntax 
> 
> \* Syntax Definitions: Fixed an infinite loop that could occur with branch points 
> 
> \* API: Fixed on\_pre\_close() being called after the view had been removed from the window 
> 
> \* API: Updated Python to 3.8.6

Host system configuration:

   \* Version of Sublime Text: 4087

   \* OS: macOS 10.15.6

   \* Python version: 3.8.5

\<summary>

Logs:

**Error loading syntax file "Packages/Djaneiro/Syntaxes/HTML (Django).tmLanguage": Apparent recursion within a with\_prototype action: 25000 context sanity limit hit**

\</summary>

**Comment by squ1b3r** [comment]
Hi. Thanks for reporting. Unfortunately, I cannot reproduce this. I just downloaded that exact build and everything loads and works fine. Trying to google for that error I found a couple of old issues with other packages that were causing this error. For example CSS3 package. Can you try to remove any packages that might cause this (highlighting related packages) and see if that works?

**Comment by Afrowave** [comment]
Alrighty,

I did the usual. I removed my ST(3) Application Support and removed all my ST versions. I downloaded ST4 4087, added my license, installed Djaneiro and added Emmet just for kicks and everything worked as it should.  
  
Thanks for the hint. 😃

**Comment by squ1b3r** [comment]
Glad that it worked :)

**Comment by ValentinCreative** [comment]
I had the exact same error and found out that the conflict came from "JavaScriptNext - ES6 Syntax"
