### ISSUE TITLE
Indentation is wrong

### ISSUE THREAD

**Issue by lifeiscontent** [squ1b3r/Djaneiro#26]
When i am using sublime text 2, and I re-indent the lines the python tags don't indent and they break the html indentation.

**Comment by ad-m** [comment]
I am would reopen discussion about how djaneiro support indentation. I believe fg. for loops body should be indentent like in "HTML (Twig)".

I recorded screencast too. Here is it: http://files.jawne.info.pl/private_html/2015_08_b60c1c8e303d0a9267ef99d901ab9e5a4cfd0239
