### ISSUE TITLE
Limited scope for tags

### ISSUE THREAD

**Issue by Kronuz** [squ1b3r/Djaneiro#3]
Django tags are limited in scope... one should be able to have django tags anywhere (even in CSS or Javascript or in HTML attributes or inside HTML tags)

I also use SCSS so I have to modify HTML.tmLanguage every time too, to include `source.scss` instead of `source.css`. That's other problem, but I was wondering... do you know how extensible can these .tmLanguage files become? do you know is there a scheme of inheritance of some sort? Because if so, Django4ST2 should override stuff set up in HTML.tmLanguage, and I can't think of a proper way of doing that and at the same time override the CSS (or in my case SCSS) and Javascript to add django tags to those too.

**Comment by scuml** [comment]
This can be closed with the latest release.
