### ISSUE TITLE
Djaneiro not active by default for html files. 

### ISSUE THREAD

**Issue by hitokiri82** [squ1b3r/Djaneiro#34]
Hello. 

I dont know if I'm doing something wrong here. But the only way I have found to make this work is by manually selecting HTML (Django) Syntax from the Djaneiro syntax menu in ST2.
Is this the only way to activate this package?

If I dont do it manually none of the snippets are available when I open an html file. And if I do block+tab i will get <blockquote></blockquote> instead of the Django block snippet. 

Any thoughts?

**Comment by samakshjain** [comment]
Anyone with this problem can solve this by clicking 'html' at the bottom right corner of ST and selecting:
'Open all with current extension as' -> HTML(django)

**Comment by abd-Hirz** [comment]
thanks **samakshjaiin**, it's working as you instruct

**Comment by Cell20** [comment]
Thanks, samakshjain. I was searching how to activate djaneiro but its a simple step. Thanks!
