### ISSUE TITLE
Changing font color and styles?

### ISSUE THREAD

**Issue by deronsizemore** [squ1b3r/Djaneiro#36]
Hi,

Sorry if this is the wrong place for this, I couldn't find another way to contact anyone. This isn't so much of an "issue" as it's just me wanting to change a few styles. How can I change the styles, i.e., colors, font styles, etc.?

Thanks

**Comment by kspacja** [comment]
Could you tell how to theme?

**Comment by squ1b3r** [comment]
Open your ".theme" file and change anything you want. There are tons of tutorials and manuals on how to do that.
