### ISSUE TITLE
Block code folding

### ISSUE THREAD

**Issue by darbula** [squ1b3r/Djaneiro#56]
It would be great if code could be folded on `{% block ... %}...{% endblock ... %}`.

**Comment by scuml** [comment]
Code folding is based on indentation and not available to modify in the API.  

As long as the content inside the block is indented, you'll be able to fold.

![Screen Shot 2022-09-15 at 7 43 20 AM](https://user-images.githubusercontent.com/1790447/190395066-002a3938-ebff-4957-822b-4512bba47f63.png)
