### ISSUE TITLE
Incorrect ID attribute highlighting

### ISSUE THREAD

**Issue by ethanal** [squ1b3r/Djaneiro#69]
This example works correctly.
![screen shot 2014-08-07 at 6 48 02 pm](https://cloud.githubusercontent.com/assets/941041/3850413/edd9d4c6-1e84-11e4-9812-a11b31221950.png)

When the ".id == " is followed by a variable or number instead of a quoted string literal, the code up until the next quotation mark is not highlighted correctly.
![screen shot 2014-08-07 at 6 38 53 pm](https://cloud.githubusercontent.com/assets/941041/3850350/0d0b6054-1e84-11e4-8ac7-dcdc5a861639.png)

Here's an example without the quotation marks.
![screen shot 2014-08-07 at 6 39 15 pm](https://cloud.githubusercontent.com/assets/941041/3850351/0d11a900-1e84-11e4-9bef-14e80a763e92.png)

This issue appears to only happen for the id attribute.

**Comment by squ1b3r** [comment]
![screenshot 2015-01-19 03 11 35](https://cloud.githubusercontent.com/assets/221821/5794281/f0268f64-9f88-11e4-9d1e-2d95e4ce6718.png)

That's because your HTML is invalid. You cannot do <option selected>foobar<option/>
