### ISSUE TITLE
var completion

### ISSUE THREAD

**Issue by iainhouston** [squ1b3r/Djaneiro#73]
I've tried various "remedies" to fix this without success - including removing two lines from `~/Library/Application Support/Sublime Text 2/Packages/HTML/HTML.sublime-completions` and restarting ST 3 anyway  this didn't seem the right approach and should be best addressed at source ... i.e. here.

In the following the `var` TAB-completes to `<var></var>` instead of `{{ }}` (but the `if` TAB-completed properly)

```
{% if error %}
    <div class="form-group has-error">
        <span class="help-block">var</span>
    </div>  
{% endif %}
```

I have the  Emmet package installed also.
Sublime Text 3

**Comment by leonciokof** [comment]
Is fixed by adding this to the user settings of emmet

```json
{
	"known_html_tags": "html head title base link meta style script noscript body section nav article aside h1 h2 h3 h4 h5 h6 hgroup header footer address p hr pre blockquote ol ul li dl dt dd figure figcaption div a em strong small s cite q dfn abbr data time code samp kbd sub sup i b u mark ruby rt rp bdi bdo span br wbr ins del img iframe embed object param video audio source track canvas map area svg math table caption colgroup col tbody thead tfoot tr td th form fieldset legend label input button select datalist optgroup option textarea keygen output progress meter details summary command menu main template"
}
```

**Comment by bluethon** [comment]
@lgaticaq Thank you, it works!

**Comment by diek** [comment]
@lgaticaq perfect!
