### ISSUE TITLE
Error loading syntax file.... Error parsing plist xml...

### ISSUE THREAD

**Issue by halfnibble** [squ1b3r/Djaneiro#82]
Over time and use, the Djaneiro plugin must be uninstalled and reinstalled due to the following error appearing:
"""
Error loading syntax file "Packages/Djaneiro/Syntaxes/Python Django.tmLanguage": Error parsing plist xml: Failed to open file In file "Packages/Djaneiro/Syntaxes/Python Django.tmLanguage"
"""

Note: this was originally reported on StackOverflow, and I can confirm it occurs in SublimeText3.
Link to SO question: http://stackoverflow.com/questions/16600437/error-loading-syntax-file-when-launch-the-sublime/27165458#27165458

The frequency appears to be random. Sorry I can't be more helpful. Let me know if there is something else you want me to provide. Thanks.

**Comment by squ1b3r** [comment]
I've updated the file a bit according to original Python file and noticed that DOCTYPE wasn't exaclty the same. I've no idea if that might be the case or not but I'm closing this for now. If issue persists feel free to open it again.
