### ISSUE TITLE
Template inheritance and Javascript highlighting

### ISSUE THREAD

**Issue by jhagege** [squ1b3r/Djaneiro#83]
Hi,
Thanks a lot for this great plugin.

All my templates inherit from a base.html template.
Inside base.html, I have some blocks like {% javascript %} {% endblock %} and {% jsload %} {% endblock %}
Those are not recognized as Javascript when in templates extending base.html.

Is there any way to indicate to Djaneiro that those blocks are indeed Javascript and should be treated as such?

I hope I've been clear enough.
Thanks a lot!

**Comment by scuml** [comment]
That templating style is too arbitrary for a package to detect.  For scripts and styles, it's recommended to use blocks to declare where you want the content to reside in the page, and then open a new script tag in the child element.  

So instead of:
```
<script>
{% block javascript %}
{% endblock javascript %}
</script>
```

Refactor as:
```html
-- parent template
<script src="jquery.min.js"/>
{% block javascript %}{% endblock javascript %}

-- child template
{% block javascript %}
{{block.super}} <!-- if needed -->
<script>
  // child template javascript.
</script>
{% endblock javascript %}
```
