### ISSUE TITLE
Strange highlighting near colons on "Python Django" syntax

### ISSUE THREAD

**Issue by Pycz** [squ1b3r/Djaneiro#84]
![2015-01-13 10 35 56](https://cloud.githubusercontent.com/assets/1331077/5717361/9ff235e2-9b10-11e4-9fd8-8b54a1e428f6.png)
![2015-01-13 10 35 42](https://cloud.githubusercontent.com/assets/1331077/5717360/9fd149d6-9b10-11e4-878e-f84f3375bc9e.png)
![2015-01-13 10 37 22](https://cloud.githubusercontent.com/assets/1331077/5717369/c4b24098-9b10-11e4-8468-82296a9ec480.png)

All is ok on standard Python Syntax. Looks like comment on Python Django. Probably, the reason is spaces after any colon. After removing spaces all looks fine.

**Comment by Pycz** [comment]
I'm using Monokai.

**Comment by squ1b3r** [comment]
![screenshot 2015-01-19 02 51 59](https://cloud.githubusercontent.com/assets/221821/5794217/38b268aa-9f86-11e4-9291-84a19198b5b3.png)

I cannot reproduce this. Tried everything you showed on those pics but it works fine for me. Might it be some other plugin messing thing up?

**Comment by Pycz** [comment]
Well, yes, it was custom plugin, written by my friend and it seems like it works unproperly.
