### ISSUE TITLE
Add option to prettify django template.

### ISSUE THREAD

**Issue by kaflesudip** [squ1b3r/Djaneiro#85]
Would love to see a feature to prettify Django Html Templates the way plugins like HTMLPrettify does.

**Comment by squ1b3r** [comment]
Well, that sounds nice but HTMLPrettify uses node.js to do the beautification, which I don't really like, and the main issue there would that I would have to write something to deal with Django Template syntax which would a great pain to do. So I don't think this will be in plans anytime soon. Sorry.
