### ISSUE TITLE
Mirror cursor on ModelField name and first argument

### ISSUE THREAD

**Issue by thongly** [squ1b3r/Djaneiro#92]
In keeping with not ever repeating ourselves, I was wondering if anyone else would find it useful to have ModelFields such as `CharField` include a mirrored cursor for [the optional first argument for verbose name](https://docs.djangoproject.com/en/1.8/topics/db/models/#verbose-field-names).

If so, I would also suggest that we automatically wrap the `verbose_name` in the `_` for `ugettext` convention as seen in the [first example in the docs](https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#standard-translation)

I would be happy to submit a pull request.

**Comment by squ1b3r** [comment]
Had that before actually and people didn't like it. Had to remove it.
