### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by OnkelTem** [squ1b3r/Djaneiro#98]
ST3 here.
Specifically, how/when to use the stuff like :
1) `autoescape	{% autoescape %} {% autoescape %}`
2) `super	{{ block.super }}`
3) Snippets for `Django Views` and similar
4) completions like `db_index`?

**Comment by squ1b3r** [comment]
I'm not even sure what exactly are you asking here. Do you expect me to teach you how to use Django or Djaneiro?

**Comment by OnkelTem** [comment]
@squ1b3r 

How to make use of those?

**Comment by squ1b3r** [comment]
As any other snippet (using Tab) and autocomplete (using ctrl + space). Seriously man, your questions has nothing to do with Djaneiro.

**Comment by OnkelTem** [comment]
What exactly should I type to get any of this working:
![] (https://sc-cdn.scaleengine.net/i/c6e82a4372cad2727b097c62620cd185.png])

**Comment by squ1b3r** [comment]
Well, obviosly, because it's templetetags for Django Templates.
